project:
  type: website
  output-dir: docs 
website:
  title: "my_portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: blog
      - href: about.qmd
        text: about
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



